Implemented UserService and UserDao
vlykhvar/springBoot pull request #1
Opened 2021-02-08 17:38 UTC by vlykhvar

Created a Main class.
Configured ApplicationContext
Configured DataSource

2021-02-08 17:55 UTC, Ketch92 approved these changes

2021-02-09 07:41 UTC, Sofasmile requested changes

2021-02-09 07:41 UTC, Sofasmile commented on src/main/java/dao/impl/UserDaoImpl.java
> +        return sessionFactory
let's use try with resources here

2021-02-09 07:41 UTC, Sofasmile commented on src/main/java/dao/impl/UserDaoImpl.java
> +    private SessionFactory sessionFactory;
https://mate-academy.github.io/jv-program-fulltime/04_spring/checklist/hw_01.html
> What is better: setter, constructor, or field injection? Think why.

2021-02-09 08:02 UTC, Sofasmile requested changes

2021-02-09 08:02 UTC, Sofasmile commented on src/main/java/service/impl/UserServiceImpl.java
> +    private UserDao userDao;
?

2021-02-09 09:26 UTC, Sofasmile approved these changes

2021-02-09 12:25 UTC, merged